version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html

hooks:
   ApplicationStop:
     - location: scripts/stop-server.sh
       runas: root
   ApplicationStart:
     - location: scripts/start-server.sh
       runas: root  
   AfterInstall:
     - location: scripts/config-app.sh
       timeout: 30
       runas: root
