version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/html

hooks:
   ApplicationStop:
     - location: scripts/stop-server.sh
       runas: ubuntu
   AfterInstall:
     - location: scripts/config-app.sh
       runas: ubuntu
   ApplicationStart:
     - location: scripts/start-server.sh
       runas: ubuntu
       timeout: 30
       
