version: 0.2
run-as: root
env:
  parameter-store:
    a: "/pankaj/dbname"
    b: "/pankaj/username"
    c: "/pankaj/password"
    d: "/pankaj/localhost-name"
phases:
  install:
    commands:
      - sudo apt-get update -y 
  pre_build:
    commands:
      - sudo sed 's/database_name_here/a/' var/www/html/wordpress/wp-config.php
      - sudo sed 's/username_here/b/' var/www/html/wordpress/wp-config.php
      - sudo sed 's/password_here/c/' var/www/html/wordpress/wp-config.php
      - sudo sed 's/localhost/d/' var/www/html/wordpress/wp-config.php

      
  build:
    commands:
      - echo Build is started 
      
  post_build:
    commands:
      - echo Build is completed 
artifacts:
  files:
    - '**/*'
